"""'添加头像字段'

Revision ID: 5a172acfa112
Revises: bd480a0be6d2
Create Date: 2016-06-06 22:07:05.146629

"""

# revision identifiers, used by Alembic.
revision = '5a172acfa112'
down_revision = 'bd480a0be6d2'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_big', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('avatar_small', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_small')
    op.drop_column('users', 'avatar_big')
    ### end Alembic commands ###
