"""'用户注册与登陆'

Revision ID: 73fd78b1c7f4
Revises: ca50b562fb0b
Create Date: 2016-05-27 15:26:37.282227

"""

# revision identifiers, used by Alembic.
revision = '73fd78b1c7f4'
down_revision = 'ca50b562fb0b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'email')
    ### end Alembic commands ###
