"""'添加推荐表'

Revision ID: b45ee53533a7
Revises: 73a6311c58cd
Create Date: 2016-06-16 12:32:44.154998

"""

# revision identifiers, used by Alembic.
revision = 'b45ee53533a7'
down_revision = '73a6311c58cd'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recommends',
    sa.Column('prim_game_id', sa.Integer(), nullable=False),
    sa.Column('rel_game_id', sa.Integer(), nullable=False),
    sa.Column('correlation', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['prim_game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('prim_game_id', 'rel_game_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recommends')
    ### end Alembic commands ###
