"""'添加用户邮件确认功能'

Revision ID: b49bd67b5652
Revises: 73fd78b1c7f4
Create Date: 2016-05-28 16:16:44.741670

"""

# revision identifiers, used by Alembic.
revision = 'b49bd67b5652'
down_revision = '73fd78b1c7f4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
