"""'添加文章的html格式字段'

Revision ID: d871e23a9c83
Revises: 34c683aff77b
Create Date: 2016-06-04 20:29:35.023851

"""

# revision identifiers, used by Alembic.
revision = 'd871e23a9c83'
down_revision = '34c683aff77b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
