"""'添加游戏模型'

Revision ID: e3d2e6ac7953
Revises: f59bdbd6c79a
Create Date: 2016-06-10 00:36:29.040605

"""

# revision identifiers, used by Alembic.
revision = 'e3d2e6ac7953'
down_revision = 'f59bdbd6c79a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_ch', sa.String(length=128), nullable=True),
    sa.Column('name_en', sa.String(length=128), nullable=True),
    sa.Column('game_type', sa.String(length=64), nullable=True),
    sa.Column('producer', sa.String(length=64), nullable=True),
    sa.Column('publisher', sa.String(length=64), nullable=True),
    sa.Column('release_time', sa.Date(), nullable=True),
    sa.Column('introduction', sa.Text(), nullable=True),
    sa.Column('cover', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_ch'),
    sa.UniqueConstraint('name_en')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('games')
    ### end Alembic commands ###
